#!/usr/bin/env python3
"""
_generateFromDefinitions.py

Derives the IG model from the definitions in input/fsh/definitions/:

  ObservationDefinitions + ValueSets + KpiDefinitions + DatasetDefinitions
        |
        v
  input/fsh/generated/Model.fsh      one profile per resource type, the code
                                     value sets, one invariant per
                                     ObservationDefinition
  input/fsh/generated/Exports.fsh    per dataset: a Group (cohort as bulk-data
                                     member-filters) and a Parameters
                                     (_type, _typeFilter, _elements)
  input/pagecontent/datasets.md      overview + derived model
  input/pagecontent/dataset-<id>.md  one readable page per dataset

Run it before SUSHI. The generated files are committed, so a plain `sushi .`
keeps working; regenerate whenever a definition changes.

  py _generateFromDefinitions.py          (Windows)
  python3 _generateFromDefinitions.py

Needs SUSHI on the PATH (the definitions are compiled with it, so every FSH
feature is supported without a second parser). Standard library only.
"""

import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FSH_DIR = ROOT / "input" / "fsh"
DEF_DIR = FSH_DIR / "definitions"
GEN_DIR = ROOT / "input" / "fsh" / "generated"
PAGE_DIR = ROOT / "input" / "pagecontent"

MEMBER_FILTER_URL = "http://hl7.org/fhir/uv/bulkdata/StructureDefinition/member-filter"
OD_COMPONENT_EXT = "od-component"
HEADER = "GENERATED by _generateFromDefinitions.py from input/fsh/definitions/ - do not edit."

# Resource types that get a generated profile, with the element that carries
# their code and every top-level element of the R4 resource. Elements that no
# KPI asks for are closed (0..0) in the profile; `keep` is always allowed.
RESOURCES = {
    "Patient": dict(
        code=None, subject=False, keep=set(),
        elements=["identifier", "active", "name", "telecom", "gender", "birthDate", "deceased[x]", "address",
                  "maritalStatus", "multipleBirth[x]", "photo", "contact", "communication",
                  "generalPractitioner", "managingOrganization", "link"]),
    "Observation": dict(
        code="code", keep={"status", "code", "subject"},
        elements=["identifier", "basedOn", "partOf", "status", "category", "code", "subject", "focus",
                  "encounter", "effective[x]", "issued", "performer", "value[x]", "dataAbsentReason",
                  "interpretation", "note", "bodySite", "method", "specimen", "device", "referenceRange",
                  "hasMember", "derivedFrom", "component"]),
    "Condition": dict(
        code="code", keep={"code", "subject"},
        elements=["identifier", "clinicalStatus", "verificationStatus", "category", "severity", "code",
                  "bodySite", "subject", "encounter", "onset[x]", "abatement[x]", "recordedDate",
                  "recorder", "asserter", "stage", "evidence", "note"]),
    "Procedure": dict(
        code="code", keep={"status", "code", "subject"},
        elements=["identifier", "instantiatesCanonical", "instantiatesUri", "basedOn", "partOf", "status",
                  "statusReason", "category", "code", "subject", "encounter", "performed[x]", "recorder",
                  "asserter", "performer", "location", "reasonCode", "reasonReference", "bodySite",
                  "outcome", "report", "complication", "complicationDetail", "followUp", "note",
                  "focalDevice", "usedCode", "usedReference"]),
}

REF = re.compile(r"\{(od|vs):([^}]+)\}")


TODAY = re.compile(r"\{today(?:([+-])(\d+)([dmy]))?\}")


def fill_today(text, today):
    """Replace {today}, {today-18y}, {today+3m}, {today-90d} by a concrete date (the exporter does this per run)."""
    import calendar
    import datetime

    def one(m):
        if not m.group(1):
            return today.isoformat()
        n = int(m.group(2)) * (1 if m.group(1) == "+" else -1)
        unit = m.group(3)
        if unit == "d":
            return (today + datetime.timedelta(days=n)).isoformat()
        months = n * (12 if unit == "y" else 1)
        y, mo = divmod(today.year * 12 + today.month - 1 + months, 12)
        day = min(today.day, calendar.monthrange(y, mo + 1)[1])
        return datetime.date(y, mo + 1, day).isoformat()

    return TODAY.sub(one, text)


def is_url(s):
    return s.startswith(("http://", "https://"))


def unpinned(canonical):
    return canonical.split("|")[0].split("--")[0]


def load_external():
    """ValueSets maintained outside the repo (see _syncValueSets.py), by key."""
    sys.path.insert(0, str(ROOT))
    from _syncValueSets import load  # the manifest reader lives with the sync script
    return {e["key"]: e for e in load()["valuesets"]}


def pinned_ref(entry):
    """The canonical a profile or query must use: the pinned version of an external ValueSet."""
    if entry["source"] == "decor" or not entry.get("version"):
        return entry["canonical"]
    return f"{entry['canonical']}|{entry['version']}"


class DefinitionError(Exception):
    pass


# ---------------------------------------------------------------------------
# Compile the definitions with SUSHI and load the resulting JSON
# ---------------------------------------------------------------------------
def sushi_config_value(key):
    m = re.search(rf"^{key}:\s*(.+?)\s*$", (ROOT / "sushi-config.yaml").read_text(encoding="utf-8"), re.M)
    if not m:
        raise DefinitionError(f"{key} not found in sushi-config.yaml")
    return m.group(1).strip("\"'")


def compile_definitions():
    sushi = shutil.which("sushi")
    if not sushi:
        raise DefinitionError("SUSHI not found on PATH (npm install -g fsh-sushi)")
    tmp = Path(tempfile.mkdtemp(prefix="defs-"))
    # The whole FSH tree (minus generated/) with the real config, so value sets, profiles and
    # logical models defined next to the definitions resolve.
    shutil.copytree(FSH_DIR, tmp / "input" / "fsh", ignore=shutil.ignore_patterns("generated"))
    cfg = (ROOT / "sushi-config.yaml").read_text(encoding="utf-8")
    (tmp / "sushi-config.yaml").write_text(cfg.rstrip() + "\nFSHOnly: true\n", encoding="utf-8")
    res = subprocess.run([sushi, "build", str(tmp)], capture_output=True, text=True)
    if res.returncode != 0:
        raise DefinitionError("SUSHI failed on the definitions:\n" + res.stdout + res.stderr)
    return tmp


def load(tmp):
    out = dict(od={}, vs={}, kpi={}, dataset={})
    for f in sorted((tmp / "fsh-generated" / "resources").glob("*.json")):
        r = json.loads(f.read_text(encoding="utf-8"))
        rt = r.get("resourceType", "")
        if rt == "ObservationDefinition":
            out["od"][r["id"]] = r
        elif rt == "ValueSet":
            out["vs"][r["id"]] = r
        elif rt.endswith("/kpi-definition"):
            out["kpi"][r["id"]] = r
        elif rt.endswith("/dataset-definition"):
            out["dataset"][r["id"]] = r
    return out


# ---------------------------------------------------------------------------
# Resolving {od:...} / {vs:...} references
# ---------------------------------------------------------------------------
def coding_tokens(cc):
    return [f"{c['system']}|{c['code']}" for c in cc.get("coding", [])]


def vs_ref_id(od):
    ref = od.get("validCodedValueSet", {}).get("reference", "")
    return ref if is_url(ref) else (ref.split("/")[-1] if ref else None)


class Resolver:
    def __init__(self, defs):
        self.defs = defs
        self.canonical = sushi_config_value("canonical")
        self.external = load_external()
        self.answers = {}  # od id -> answers added by KPI criteria (filled by derive_model)

    def vs_url(self, vs_id):
        ext = self.external
        if vs_id in self.defs["vs"]:
            pass
        elif vs_id in ext:  # maintained elsewhere (ART-DECOR, NTS): resolved to its pinned version
            return pinned_ref(ext[vs_id])
        elif is_url(vs_id):  # unregistered canonical: used as written
            for e in ext.values():
                if unpinned(e["canonical"]) == unpinned(vs_id):
                    return pinned_ref(e)
            return vs_id
        vs = self.defs["vs"].get(vs_id)
        if not vs:
            raise DefinitionError(f"ValueSet '{vs_id}' is not defined in the definitions")
        return vs.get("url") or f"{self.canonical}/ValueSet/{vs_id}"

    def od(self, od_id):
        od = self.defs["od"].get(od_id)
        if not od:
            raise DefinitionError(f"ObservationDefinition '{od_id}' is not defined in the definitions")
        return od

    def one(self, kind, body):
        if kind == "vs":
            return self.vs_url(body)
        od_id, _, attr = body.partition(".")
        od = self.od(od_id)
        if attr == "code":
            return ",".join(coding_tokens(od["code"]))
        if attr == "unit":
            return ",".join(coding_tokens(od["quantitativeDetails"]["unit"]))
        if attr == "valid":
            vs_id = vs_ref_id(od)
            if not vs_id:
                raise DefinitionError(f"ObservationDefinition '{od_id}' has no validCodedValueSet")
            return self.vs_url(vs_id)
        raise DefinitionError(f"Unknown reference {{od:{body}}} (use .code, .unit or .valid)")

    def value(self, value):
        return REF.sub(lambda m: self.one(m.group(1), m.group(2)), value)

    def query(self, criterion):
        params = [f"{p['name']}={self.value(p['value'])}" for p in criterion.get("param", [])]
        return criterion["resource"] + ("?" + "&".join(params) if params else "")


def code_sources(criterion):
    """(od ids, vs ids or URLs, literal (system, code) pairs) behind a criterion's code parameter(s).

    A code parameter may reference a definition ({od:..}, {vs:..}), name an external
    value set by URL (code:in=http://...), or list literal system|code tokens.
    """
    ods, vss, codes = [], [], []
    for p in criterion.get("param", []):
        if p["name"] == "code" or p["name"].startswith("code:"):
            for kind, body in REF.findall(p["value"]):
                (ods if kind == "od" else vss).append(body.split(".")[0] if kind == "od" else body)
            for tok in REF.sub("", p["value"]).split(","):
                tok = tok.strip()
                if not tok:
                    continue
                if p["name"].endswith(":in") and is_url(tok):
                    vss.append(tok)
                elif "|" in tok:
                    system, _, code = tok.partition("|")
                    codes.append((system, code))
    return ods, vss, codes


def answer_sources(criterion):
    """(value set ids or URLs, literal (system, code) pairs) a criterion adds as permitted answers.

    Read from value-concept parameters: `value-concept=system|code,...` lists answers inline,
    `value-concept:in={vs:..}` or a URL names a value set (local, ART-DECOR or NTS).
    """
    vss, codes = [], []
    for p in criterion.get("param", []):
        if p["name"] == "value-concept" or p["name"].startswith("value-concept:"):
            vss += [body for kind, body in REF.findall(p["value"]) if kind == "vs"]
            for tok in REF.sub("", p["value"]).split(","):
                tok = tok.strip()
                if p["name"].endswith(":in") and is_url(tok):
                    vss.append(tok)
                elif "|" in tok:
                    system, _, code = tok.partition("|")
                    codes.append((system, code))
    return vss, codes


def lower_first(s):
    return s[:1].lower() + s[1:]


# Names of generated artifacts follow the HL7 Europe / EHDS pattern: a camelCase resource name,
# a family suffix (-san) and a use-case suffix (-kpi); titles read "Resource (SAN KPI)".
def profile_name(rt):
    return f"{rt}SanKpi"


def profile_id(rt):
    return f"{lower_first(rt)}-san-kpi"


def code_vs_name(rt):
    return f"{rt}CodeSanKpi"


def code_vs_id(rt):
    return f"{lower_first(rt)}Code-san-kpi"


def answer_vs_id(od_id):
    return f"answers-{od_id}-san-kpi"


# ---------------------------------------------------------------------------
# Deriving the model from all KPI criteria
# ---------------------------------------------------------------------------
def derive_model(defs, res):
    model = {}

    def absorb(c, owner, owner_id):
        rt = c["resource"]
        if rt not in RESOURCES:
            raise DefinitionError(f"{owner}: resource {rt} has no generated profile (supported: {', '.join(RESOURCES)})")
        m = model.setdefault(rt, dict(ods=[], vss=[], codes=[], elements=[], kpis=[]))
        ods, vss, codes = code_sources(c)
        for code in codes:
            if code not in m["codes"]:
                m["codes"].append(code)
        a_vss, a_codes = answer_sources(c)
        for o in ods:
            res.od(o)
            if o not in m["ods"]:
                m["ods"].append(o)
            if a_vss or a_codes:  # answers a criterion adds to this measurement
                a = res.answers.setdefault(o, dict(vss=[], codes=[]))
                for v in a_vss:
                    res.vs_url(v)
                    if v not in a["vss"]:
                        a["vss"].append(v)
                for code in a_codes:
                    if code not in a["codes"]:
                        a["codes"].append(code)
        for v in vss:
            res.vs_url(v)
            if v not in m["vss"]:
                m["vss"].append(v)
        for e in c.get("element", []):
            if e not in RESOURCES[rt]["elements"]:
                raise DefinitionError(f"{owner}: '{e}' is not a top-level element of {rt}")
            if e not in m["elements"]:
                m["elements"].append(e)
        if owner_id not in m["kpis"]:
            m["kpis"].append(owner_id)

    for kpi in defs["kpi"].values():
        for c in kpi["criteria"]:
            absorb(c, f"KPI '{kpi['id']}'", kpi["id"])
    for ds in defs["dataset"].values():  # data a dataset releases outside any KPI
        for c in ds.get("include", []):
            absorb(c, f"Dataset '{ds['id']}'", ds["id"])
    return model


def vs_label(res, vs_id):
    """Short display name for a ValueSet reference: the registry key when there is one."""
    if is_url(vs_id):
        for k, e in res.external.items():
            if unpinned(e["canonical"]) == unpinned(vs_id):
                return k
    return vs_id


def od_title(od):
    return od.get("preferredReportName") or od["code"]["coding"][0].get("display", od["id"])


def component_ods(defs, od):
    out = []
    for ext in od.get("extension", []):
        if ext.get("url", "").endswith("/" + OD_COMPONENT_EXT):
            out.append(ext["valueReference"]["reference"].split("/")[-1])
    return out


def fhirpath_code_match(cc):
    parts = [f"system='{c['system']}' and code='{c['code']}'" for c in cc["coding"]]
    if len(parts) > 1:
        parts = [f"({p})" for p in parts]
    return "code.coding.where(" + " or ".join(parts) + ").exists()"


def od_invariant(od_id, res):
    """The one invariant a generated profile derives from an ObservationDefinition."""
    od = res.od(od_id)
    when = fhirpath_code_match(od["code"])
    comps = component_ods(res.defs, od)
    if comps:
        checks = ["value.empty()"]
        for cid in comps:
            c = res.od(cid)
            match = fhirpath_code_match(c["code"])
            sel = f"component.where({match})"
            unit = c.get("quantitativeDetails", {}).get("unit")
            cond = "value.ofType(Quantity).exists()"
            if unit:
                u = unit["coding"][0]
                cond += f" and value.ofType(Quantity).system='{u['system']}' and value.ofType(Quantity).code='{u['code']}'"
            checks.append(f"{sel}.where({cond}).count() = 1")
        return when, " and ".join(checks), "panel with components: no value[x]; each component carries its quantity and unit"
    types = od.get("permittedDataType", [])
    if "Quantity" in types:
        unit = od.get("quantitativeDetails", {}).get("unit")
        cond = ["value.ofType(Quantity).exists()"]
        desc = "value[x] is a Quantity"
        if unit:
            u = unit["coding"][0]
            cond += [f"value.ofType(Quantity).system='{u['system']}'", f"value.ofType(Quantity).code='{u['code']}'"]
            desc += f" in {u['code']}"
        return when, " and ".join(cond), desc
    if "CodeableConcept" in types:
        cond = ["value.ofType(CodeableConcept).exists()"]
        desc = "value[x] is a CodeableConcept"
        vs_id = vs_ref_id(od)
        if od_id in res.answers:  # KPIs add answers: the permitted set is the generated union
            cond.append(f"value.ofType(CodeableConcept).memberOf('{res.canonical}/ValueSet/{answer_vs_id(od_id)}')")
            desc += f" from {answer_vs_id(od_id)}"
        elif vs_id:
            cond.append(f"value.ofType(CodeableConcept).memberOf('{res.vs_url(vs_id)}')")
            desc += f" from {vs_label(res, vs_id)}"
        return when, " and ".join(cond), desc
    if types:
        t = types[0]
        return when, f"value.ofType({t}).exists()", f"value[x] is a {t}"
    return when, "value.exists()", "value[x] is present"


# ---------------------------------------------------------------------------
# FSH output
# ---------------------------------------------------------------------------
def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_model_fsh(defs, res, model):
    L = [f"// {HEADER}", ""]
    for rt, m in model.items():
        cfg = RESOURCES[rt]
        L += ["// " + "-" * 69, f"// {rt}", "// " + "-" * 69, ""]
        if cfg["code"]:
            L += [f"ValueSet: {code_vs_name(rt)}", f"Id: {code_vs_id(rt)}",
                  f'Title: "{rt} code (SAN KPI)"',
                  f'Description: "Every code a KPI definition asks for on {rt}. The union of the ObservationDefinition codes and the value sets referenced by the {rt} criteria of all KPI definitions."',
                  "* ^status = #draft", "* ^experimental = false"]
            for o in m["ods"]:
                for c in res.od(o)["code"]["coding"]:
                    L.append(f"* {c['system']}#{c['code']} {q(c.get('display', c['code']))}")
            for system, code in m["codes"]:
                L.append(f"* {system}#{code}")
            for v in m["vss"]:
                L.append(f"* include codes from valueset {res.vs_url(v)}")
            L.append("")

        invs = []
        if rt == "Observation":
            for o, a in res.answers.items():
                od = res.od(o)
                L += [f"ValueSet: {re.sub('[^A-Za-z0-9]', '', 'Answers-' + o.title() + '-SanKpi')}", f"Id: {answer_vs_id(o)}",
                      f'Title: "Answers: {od_title(od)} (SAN KPI)"',
                      f'Description: "Permitted coded answers for {od_title(od)}: the ObservationDefinition\'s own valid value set (when it has one) together with the answers KPI definitions list inline or by value set."',
                      "* ^status = #draft", "* ^experimental = false"]
                if vs_ref_id(od):
                    L.append(f"* include codes from valueset {res.vs_url(vs_ref_id(od))}")
                L += [f"* {system}#{code}" for system, code in a["codes"]]
                L += [f"* include codes from valueset {res.vs_url(v)}" for v in a["vss"]]
                L.append("")
            for o in m["ods"]:
                invs.append((f"{profile_id(rt)}-{o}", o) + od_invariant(o, res))
            for name, o, when, then, desc in invs:
                L += [f"Invariant: {name}",
                      f"Description: {q(od_title(res.od(o)) + ': ' + desc)}",
                      "Severity: #error",
                      f"Expression: {q(when + ' implies (' + then + ')')}", ""]

        m["invariants"] = invs
        closed = [e for e in cfg["elements"] if e not in m["elements"] and e not in cfg["keep"]]
        m["closed"] = closed
        L += [f"Profile: {profile_name(rt)}", f"Parent: {rt}", f"Id: {profile_id(rt)}",
              f'Title: "{rt} (SAN KPI)"',
              f'Description: "The one {rt} profile of the model, generated from the KPI and dataset definitions.'
              + (f' Allowed codes: {code_vs_name(rt)}.' if cfg["code"] else "") + ' Elements nothing asks for are closed."',
              "* ^status = #draft"]
        if cfg["code"]:
            L.append(f"* {cfg['code']} from {code_vs_name(rt)} (required)")
        if cfg.get("subject", True):
            L += ["* subject 1..1", "* subject only Reference(Patient)"]
        L += [f"* {e} 0..0" for e in closed]
        L += [f"* obeys {name}" for name, *_ in invs]
        L.append("")
    return "\n".join(L)


def is_code_param(name):
    return name == "code" or name.startswith("code:")


def rolled_up_filters(res, criteria):
    """Resolved _typeFilter strings. Criteria on the same resource that differ only in their code
    parameter become one filter with the codes as a comma-separated list (FHIR search: OR)."""
    groups = {}
    for c in criteria:
        params = [(p["name"], res.value(p["value"])) for p in c.get("param", [])]
        codes = [(n, v) for n, v in params if is_code_param(n)]
        if len(codes) == 1:
            name, value = codes[0]
            others = tuple((n, v) for n, v in params if not is_code_param(n))
            g = groups.setdefault((c["resource"], name, others), [])
            for v in value.split(","):
                if v not in g:
                    g.append(v)
        else:
            groups.setdefault((c["resource"], None, tuple(params)), [])
    out = []
    for (resource, code_name, others), values in groups.items():
        parts = ([f"{code_name}={','.join(values)}"] if code_name else []) + [f"{n}={v}" for n, v in others]
        out.append(resource + ("?" + "&".join(parts) if parts else ""))
    return out


def exports(defs, res, ds):
    """Resolved export request of one dataset: Group filters and Parameters."""
    cohort = [res.query(c) for c in ds["cohort"]["criteria"]]
    types, elements, criteria = [], [], []
    sources = []
    for kid in ds["kpi"]:
        kpi = defs["kpi"].get(kid)
        if not kpi:
            raise DefinitionError(f"Dataset '{ds['id']}': KPI '{kid}' is not defined")
        sources += kpi["criteria"]
    sources += ds.get("include", [])  # data the dataset releases outside any KPI
    for c in sources:
        if c["resource"] not in types:
            types.append(c["resource"])
        criteria.append(c)
        for e in c.get("element", []):
            item = f"{c['resource']}.{e}"
            if item not in elements:
                elements.append(item)
    return dict(cohort=cohort, types=types, filters=rolled_up_filters(res, criteria), elements=elements)


def gen_exports_fsh(defs, res):
    L = [f"// {HEADER}", ""]
    for ds in defs["dataset"].values():
        x = exports(defs, res, ds)
        i = ds["id"]
        L += [f"Instance: {i}-cohort", "InstanceOf: Group", "Usage: #definition",
              f'Title: "{ds["title"]} cohort (generated)"',
              f'Description: "Cohort of the {ds["title"]} dataset as bulk-data member-filters."',
              "* type = #person", "* actual = true", f"* name = {q(ds['title'] + ' cohort')}"]
        for expr in x["cohort"]:
            L += [f"* modifierExtension[+].url = {q(MEMBER_FILTER_URL)}",
                  "* modifierExtension[=].valueExpression.language = #application/x-fhir-query",
                  f"* modifierExtension[=].valueExpression.expression = {q(expr)}"]
        L += ["", f"Instance: {i}-export", "InstanceOf: Parameters", "Usage: #definition",
              f'Title: "{ds["title"]} export parameters (generated)"',
              f'Description: "_type, _typeFilter and _elements of the {ds["title"]} export."',
              "* parameter[+].name = \"_type\"", f"* parameter[=].valueString = {q(','.join(x['types']))}"]
        for f in x["filters"]:
            L += ["* parameter[+].name = \"_typeFilter\"", f"* parameter[=].valueString = {q(f)}"]
        L += ["* parameter[+].name = \"_elements\"", f"* parameter[=].valueString = {q(','.join(x['elements']))}", ""]
    return "\n".join(L)


# ---------------------------------------------------------------------------
# Markdown pages
# ---------------------------------------------------------------------------
def md_params(criterion):
    rows = ["| Parameter | Value |", "|---|---|"]
    for p in criterion.get("param", []):
        rows.append(f"| `{p['name']}` | `{p['value']}` |")
    return rows if len(rows) > 2 else ["_No search parameters: every record of this type._"]


def md_postfilters(pfs):
    out = []
    for p in pfs:
        out.append(f"- {p['description'].strip()}")
        if p.get("expression"):
            out.append(f"  - `{p['expression']}`")
    return out


def gen_dataset_page(defs, res, ds, x):
    i, T = ds["id"], ds["title"]
    L = [f"<!-- {HEADER} -->", "",
         f"## {T} dataset", "", ds.get("description", "").strip(), "",
         f"Version {ds['version']} · definition: [{i}](Binary-{i}.html) · "
         f"generated: [Group](Group-{i}-cohort.html), [Parameters](Parameters-{i}-export.html)",
         ""]
    L += ["---", "", "### Cohort", ""]
    if ds["cohort"].get("description"):
        L += [ds["cohort"]["description"].strip(), ""]
    L += ["A patient is in the Group when every criterion below is satisfied. "
          "Each criterion becomes one bulk-data `member-filter` modifier extension on the Group; the Bulk Data IG defines several filters as all of them having to match.", ""]
    for n, c in enumerate(ds["cohort"]["criteria"], 1):
        L += [f"**Criterion {n}: {c['resource']}**", ""] + md_params(c) + ["", "```text", x["cohort"][n - 1], "```", ""]
    if ds["cohort"].get("postFilter"):
        L += ["**Post-query cohort filters**", ""] + md_postfilters(ds["cohort"]["postFilter"]) + [""]

    L += ["---", "", "### KPI definitions", "",
          "The data each KPI needs. Criteria are role-neutral; the same criterion in two KPIs is queried once.", ""]
    for kid in ds["kpi"]:
        k = defs["kpi"][kid]
        L += [f"#### {k['title']}", "",
              f"`{kid}` · version {k['version']} · definition: [{kid}](Binary-{kid}.html)", ""]
        if k.get("description"):
            L += [k["description"].strip(), ""]
        for n, c in enumerate(k["criteria"], 1):
            L += [f"**Criterion {n}: {c['resource']}**", ""] + md_params(c) + [""]
            L += ["Resolved:", "", "```text", res.query(c), "```", ""]
            if c.get("element"):
                L += ["Elements: " + ", ".join(f"`{e}`" for e in c["element"]), ""]
        if k.get("postFilter"):
            L += ["**Post-query filters**", ""] + md_postfilters(k["postFilter"]) + [""]

    if ds.get("include"):
        L += ["---", "", "### Included data", "",
              "Data the dataset releases that does not belong to a KPI. It is part of the export and of the derived model like a KPI criterion.", ""]
        for n, c in enumerate(ds["include"], 1):
            L += [f"**{c['resource']}**", ""] + md_params(c) + [""]
            L += ["Resolved:", "", "```text", res.query(c), "```", ""]
            if c.get("element"):
                L += ["Elements: " + ", ".join(f"`{e}`" for e in c["element"]), ""]

    L += ["---", "", "### Export request", "",
          "Resolved from the cohort and the KPI definitions above. Criteria that differ only in their code are rolled up into one filter with a list of codes. "
          "`{today}`, `{today-18y}` and `{today-90d}` are replaced by a concrete date and other `{placeholders}` are filled in by the exporter when the request is sent.", "",
          "**`_type`**", "", f"`{','.join(x['types'])}`", "", "**`_typeFilter`**", "", "```text"]
    L += x["filters"] + ["```", "", "**`_elements`**", "", "```text", ",".join(x["elements"]), "```", "",
          "Every `_typeFilter` and every element above must be covered by the de-identification ruleset, see "
          "[De-identification](deidentification.html#core-principles).", "",
          "---", "", "### Request sequence", "",
          "The export is a sequence of ordinary FHIR requests, executed in this order by the client. "
          "They cannot be combined in one Bundle: `$export` is asynchronous and a transaction cannot wait for a Group "
          "that is created asynchronously. Fill in every `{placeholder}` in the Group and the Parameters first.", "",
          f"1. **Create the cohort Group.** `PUT [base]/Group/{i}-cohort` with the "
          f"[Group](Group-{i}-cohort.html). A `PUT` fixes the id, so step 3 does not need to read it from a response. "
          "A server that creates the Group asynchronously (Bulk Cohort) answers with a status location; poll it until it is complete.",
          "2. **Wait for the Group.** Continue only when the Group exists and its members are resolved.",
          f"3. **Start the export.** `POST [base]/Group/{i}-cohort/$export` with header `Prefer: respond-async` and the "
          f"[Parameters](Parameters-{i}-export.html) as body. The answer is a status location.",
          "4. **Wait for the export.** Poll the status location until it returns the manifest.",
          "5. **Download** the files listed in the manifest.", "",
          "How the de-identification ruleset reaches the server is not part of the Bulk Data specification and is not "
          "decided here.", ""]
    return "\n".join(L)


def ext_link(res, v):
    """Markdown link for a ValueSet reference: a local ValueSet page, or the pinned external canonical."""
    if v in res.defs["vs"]:
        return f"[{v}](ValueSet-{v}.html)"
    url = res.vs_url(v).split("|")[0]
    return f"[{vs_label(res, v) if is_url(v) else v}]({url})"


def gen_external_section(res):
    if not res.external:
        return []
    L = ["---", "", "### External ValueSets", "",
         "Maintained outside this repository and pinned here. `_syncValueSets.py check` compares each pin with its source.", "",
         "| Key | Source | Pinned version | Mode |", "|---|---|---|---|"]
    for k, e in res.external.items():
        mode = "downloaded in the build" if e["mode"] == "download" else "reference only (not downloadable)"
        L.append(f"| [{k}]({e['canonical']}) | {e['source']} | {e.get('version') or 'not versioned (implicit)'} | {mode} |")
    return L + [""]


def gen_overview_page(defs, res, model):
    L = [f"<!-- {HEADER} -->", "", "## Datasets", "",
         "One dataset per disease area. Each dataset is exported on its own Group; its definition, cohort, "
         "KPIs, post-query filters and resolved export request are on its page. How the definitions work is "
         "described under [KPI definitions](kpi-definitions.html).", "",
         "| Dataset | Version | KPIs | Cohort criteria |", "|---|---|---|---|"]
    for ds in defs["dataset"].values():
        L.append(f"| [{ds['title']}]({ds['id']}.html) | {ds['version']} | {len(ds['kpi'])} | {len(ds['cohort']['criteria'])} |")
    L += ["", "### KPI definitions in use", "", "| KPI | Version | Used in |", "|---|---|---|"]
    for kid, k in defs["kpi"].items():
        used = ", ".join(f"[{d['title']}]({d['id']}.html)" for d in defs["dataset"].values() if kid in d["kpi"]) or "_none_"
        L.append(f"| [{k['title']}](Binary-{kid}.html) | {k['version']} | {used} |")
    L += ["", "---", "", "### Derived model", "",
          "The union of all KPI definitions determines the model. One profile per resource type is generated; "
          "it accepts exactly the codes the KPIs ask for and closes every element no KPI asks for.", ""]
    for rt, m in model.items():
        L += [f"#### {rt}", "",
              f"Profile: [{rt} (SAN KPI)](StructureDefinition-{profile_id(rt)}.html)"
              + (f" · code value set: [{rt} code (SAN KPI)](ValueSet-{code_vs_id(rt)}.html)" if RESOURCES[rt]["code"] else "")
              + " · used by " + ", ".join(f"`{k}`" for k in m["kpis"]), ""]
        if RESOURCES[rt]["code"]:
            L += ["Code sources: " + ", ".join(
                      [f"[{o}](ObservationDefinition-{o}.html)" for o in m["ods"]] +
                      [ext_link(res, v) for v in m["vss"]] +
                      [f"`{sy}|{co}`" for sy, co in m["codes"]]), ""]
        L += ["Elements released: " + ", ".join(f"`{e}`" for e in m["elements"]), ""]
        if m["invariants"]:
            L += ["| Measurement | Constraint derived from its ObservationDefinition |", "|---|---|"]
            for name, o, _when, _then, desc in m["invariants"]:
                L.append(f"| [{od_title(res.od(o))}](ObservationDefinition-{o}.html) | {desc} (`{name}`) |")
            L.append("")
    L += gen_external_section(res)
    return "\n".join(L)


# ---------------------------------------------------------------------------
def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip("\n") + "\n", encoding="utf-8", newline="\n")
    print(f"  wrote {path.relative_to(ROOT)}")


def update_menu(defs):
    """Rewrite the Datasets dropdown of the IG menu: one entry per dataset, then the overview."""
    f = ROOT / "input" / "includes" / "menu.xml"
    text = f.read_text(encoding="utf-8")
    start, end = "<!-- datasets:start", "<!-- datasets:end -->"
    i, j = text.find(start), text.find(end)
    if i < 0 or j < 0:
        print("  WARNING: menu.xml has no datasets:start / datasets:end markers; menu not updated")
        return
    indent = "      "
    items = [f'{indent}<li>\n{indent}  <a href="{d["id"]}.html">{d["title"]}</a>\n{indent}</li>' for d in defs["dataset"].values()]
    items.append(f'{indent}<li>\n{indent}  <a href="datasets.html">All datasets and derived model</a>\n{indent}</li>')
    head = text[i:text.index("\n", i)]
    block = head + "\n" + "\n".join(items) + "\n" + indent
    new_text = text[:i] + block + text[j:]
    if new_text != text:
        f.write_text(new_text, encoding="utf-8", newline="\n")
        print(f"  wrote {f.relative_to(ROOT)}")


def show_resolved(defs, res, today):
    """Print every request of every dataset with the date placeholders filled in (nothing is written)."""
    for ds in defs["dataset"].values():
        x = exports(defs, res, ds)
        print(f"== {ds['title']} (as of {today})")
        for q_ in x["cohort"]:
            print("  member-filter:", fill_today(q_, today))
        for q_ in x["filters"]:
            print("  _typeFilter:  ", fill_today(q_, today))


def main():
    import datetime
    today = None
    if "--today" in sys.argv:
        i = sys.argv.index("--today")
        today = datetime.date.fromisoformat(sys.argv[i + 1]) if len(sys.argv) > i + 1 else datetime.date.today()
    tmp = compile_definitions()
    try:
        defs = load(tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    res = Resolver(defs)
    model = derive_model(defs, res)
    for od_id, od in defs["od"].items():  # every referenced answer set must be local or registered
        ref = vs_ref_id(od)
        if ref and is_url(ref) and not any(unpinned(e["canonical"]) == unpinned(ref) for e in res.external.values()):
            print(f"  WARNING: {od_id} refers to {ref}, which is not registered in external-valuesets.yaml")
    if today:
        show_resolved(defs, res, today)
        return

    print(f"{len(defs['od'])} ObservationDefinitions, {len(defs['vs'])} ValueSets, "
          f"{len(defs['kpi'])} KPIs, {len(defs['dataset'])} datasets")
    write(GEN_DIR / "Model.fsh", gen_model_fsh(defs, res, model))
    write(GEN_DIR / "Exports.fsh", gen_exports_fsh(defs, res))
    write(PAGE_DIR / "datasets.md", gen_overview_page(defs, res, model))
    update_menu(defs)
    cfg = (ROOT / "sushi-config.yaml").read_text(encoding="utf-8")
    for ds in defs["dataset"].values():
        write(PAGE_DIR / f"{ds['id']}.md", gen_dataset_page(defs, res, ds, exports(defs, res, ds)))
        if f"{ds['id']}.md" not in cfg:
            print(f"  WARNING: add {ds['id']}.md under 'datasets.md' in the pages of sushi-config.yaml")


if __name__ == "__main__":
    try:
        main()
    except DefinitionError as e:
        sys.exit(f"ERROR: {e}")
